### ISSUE TITLE
Failed to import any of ... PyQt6, PySide6, PyQt5, PySide2

### ISSUE THREAD

**Issue by ko0f** [ekosman/AnomalyDetectionCVPR2018-Pytorch#203]
**Describe the bug**
When running `video_demo.py` it fails -
```
Traceback (most recent call last):
  File "video_demo.py", line 9, in <module>
    from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg
  File "/Users/.../anaconda3/envs/adCVPR18/lib/python3.8/site-packages/matplotlib/backends/backend_qt5agg.py", line 7, in <module>
    from .backend_qtagg import (    # noqa: F401, E402 # pylint: disable=W0611
  File "/Users/.../anaconda3/envs/adCVPR18/lib/python3.8/site-packages/matplotlib/backends/backend_qtagg.py", line 9, in <module>
    from .qt_compat import QT_API, _enum
  File "/Users/.../anaconda3/envs/adCVPR18/lib/python3.8/site-packages/matplotlib/backends/qt_compat.py", line 135, in <module>
    raise ImportError(
ImportError: Failed to import any of the following Qt binding modules: PyQt6, PySide6, PyQt5, PySide2
```

**To Reproduce**
1. Clone repo
2. Install anaconda dependencies, activate env
3. Run `python video_demo.py --help`

**Desktop (please complete the following information):**
 - OS: macOS Sonoma
 - Browser zsh
 - Version: latest

**Comment by ekosman** [comment]
Could you try running
```
conda install -c conda-forge pyqt==5.15.9
```

and tell if that works?

**Comment by ekosman** [comment]
This seems not to be reproducible. Please try to clone again and reopen the issue if that still happens.
