### ISSUE TITLE
TypeError: write() got an unexpected keyword argument 'start_frame'

### ISSUE THREAD

**Issue by yosagaf** [ekosman/AnomalyDetectionCVPR2018-Pytorch#25]
Hi,
Where does this error come from ? Even on AD_live perdiction I got the same error. For information on the last commit VideoIterTrain has been change to VideoIter so I made some small change

Traceback (most recent call last):
  File "video_demo.py", line 268, in <module>
    dir_list=cd3_extartion(video_parth,device=device)
  File "video_demo.py", line 89, in cd3_extartion
    features_writer.write(feature=outputs[i], video_name=vid_name, start_frame=start_frame, dir=dir)
TypeError: write() got an unexpected keyword argument 'start_frame'

**Comment by yosagaf** [comment]
Resolved, small change on feature_extractor.py with 
def store(self, feature, start_frame):
		self.data[start_frame // self.chunk_size] = list(feature.cpu().numpy())

	def write(self, feature, video_name, start_frame, dir):
		if not self.has_video():
			self._init_video(video_name, dir)

		if self._is_new_video(video_name, dir):
			self.dump()
			self._init_video(video_name, dir)
		self.store(feature, start_frame)
