### ISSUE TITLE
TypeError: __init__() takes at least 3 positional arguments (2 given)

### ISSUE THREAD

**Issue by vovantuan1999a** [ekosman/AnomalyDetectionCVPR2018-Pytorch#29]
Hi, I'm student in university.
When run video_demo.py, I had error bellow.
Can someone help how to resolve this error thanks.

Traceback (most recent call last):
  File "video_demo.py", line 283, in <module>
    dir_list=cd3_extartion(video_parth,device=device)
  File "video_demo.py", line 75, in cd3_extartion
    single_load=single_load)
  File "/content/gdrive/My Drive/DoAnChuyenNganh/AnomalyDetectionCVPR2018-Pytorch/data_loader.py", line 40, in __init__
    frames_between_clips=self.total_clip_length_in_frames)
  File "/usr/local/envs/torch/lib/python3.7/site-packages/torchvision/datasets/video_utils.py", line 55, in __init__
    self._compute_frame_pts()
  File "/usr/local/envs/torch/lib/python3.7/site-packages/torchvision/datasets/video_utils.py", line 84, in _compute_frame_pts
    for batch in dl:
  File "/usr/local/envs/torch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/usr/local/envs/torch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/usr/local/envs/torch/lib/python3.7/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
  File "av/utils.pyx", line 27, in av.utils.AVError.__init__
TypeError: __init__() takes at least 3 positional arguments (2 given)

**Comment by PHDPeter** [comment]
Hi @vovantuan1999a 
it looks like self.total_clip_length_in_frames is not a int maybe check that train_frame_interval clip_length are both int
`  train_frame_interval=int(2)
    clip_length=int(16)`

Otherwise, could you give me more information on the state of the varbule just before the error?

**Comment by PHDPeter** [comment]
Agin I think I will need a bit more information to go on then just the error out put.
could you show me the output from the feature variable just before line 104, in cd3_extartion features_writer.dump() is run?

It looks like the feature variable is not being created correctly so are you sure that you fixed the previous error or did the message just stop showing? I.e. after that part of the code you ran was fixed did you get the output you would have expected?
An error will only run when the code "can't" do what you ask it to not if the code is just doing the wrong thing.

**Comment by vovantuan1999a** [comment]
I just correct it according to your instructions that train_frame_interval = int (2) clip_length = int (16).

Here is the value of a feature before line 104:        device='cuda:0')
tensor([[0.2866, 1.4807, 0.0000,  ..., 0.0000, 1.0469, 0.0000]],
       device='cuda:0')
tensor([[0.2533, 1.4484, 0.0000,  ..., 0.0000, 1.1419, 0.0000]],
       device='cuda:0')
tensor([[0.3552, 1.3137, 0.0000,  ..., 0.0000, 1.1031, 0.0000]],
       device='cuda:0')
tensor([[0.1048, 1.3047, 0.0000,  ..., 0.0000, 1.0450, 0.0000]],
       device='cuda:0')
tensor([[0.3443, 1.3370, 0.0000,  ..., 0.0000, 1.0738, 0.0000]],
       device='cuda:0')
tensor([[0.2551, 1.4314, 0.0000,  ..., 0.0000, 0.8987, 0.0000]],
       device='cuda:0')
tensor([[0.0517, 1.5836, 0.0000,  ..., 0.0000, 1.4418, 0.0000]],
       device='cuda:0')

Thanks you
Best regards,

**Comment by ezzatmostafa96** [comment]
@vovantuan1999a   can you share the colab? thank you in advance
