### ISSUE TITLE
(Training issue) ValueError: empty range for randrange() (0,0, 0)

### ISSUE THREAD

**Issue by mikuchels** [ekosman/AnomalyDetectionCVPR2018-Pytorch#66]
Traceback (most recent call last):
  File "/home/skymind/Desktop/AnomalyDetectionCVPR2018-Pytorch/features_loader.py", line 42, in __getitem__
    feature, label = self.get_feature(index)
  File "/home/skymind/Desktop/AnomalyDetectionCVPR2018-Pytorch/features_loader.py", line 62, in get_feature
    idx = random.randint(0, len(self.features_list_normal) - 1)
  File "/root/anaconda3/envs/adCVPR18/lib/python3.7/random.py", line 222, in randint
    return self.randrange(a, b+1)
  File "/root/anaconda3/envs/adCVPR18/lib/python3.7/random.py", line 200, in randrange
    raise ValueError("empty range for randrange() (%d,%d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (0,0, 0)

Could I get help solving this?

**Comment by ekosman** [comment]
It's because `features_list_normal` is empty. Are you sure you passed the correct annotations file?
